apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapptwo
spec:
  selector:
    matchLabels:
      app: myapptwo
  replicas: 2
  template:
    metadata:
      labels:
        app: myapptwo
    spec:
      containers:
      - name: myapptwo
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
